site_name: Kraken Docs
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: red
      toggle:
        icon: material/weather-night
        name: Switch to light mode


repo_name: Gnoztis/kraken-docs
repo_url: https://github.com/Gnoztis/kraken-docs
markdown_extensions:
  - toc:
      permalink: true
  - md_in_html
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


plugins:
    - search

